<a href="https://colab.research.google.com/github/ashutoshsinha25/tensorflow-developement/blob/main/TensorFlow%20Fundamentals/00_tensorflow_fundamentals_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#In this notebook, we are going to cover fundamental concepts of tensors usning Tensorflow

More specifically, we're going to cover :
* introductions to tensors
* getting informations from tensors
* manipulating tensors
* tensors and numpy 
* using @tf.function(a way to speed up your regular python functions
* using GPUs with Tensorflow(or TPU)
* exercises to try for yourself

# Intorduction to Tensors

In [ ]:
#import tensorflow
import tensorflow as tf

print(tf.__version__)

2.7.0


In [ ]:
# create tensors with tf.constant()
scalar = tf.constant(7 )
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# check the number of dimensions of a tensor(ndim stands for nuber of dimensions)
scalar.ndim

0

In [ ]:
#create a vector 
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# check the dimension of vector
vector.ndim

1

In [ ]:
# create a matrix( has more than 1 dimensions)
matrix = tf.constant([[10,7],
                     [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
#check the dimensions
matrix.ndim

2

In [ ]:
#create another matrix 
another_matrix = tf.constant([[10.,7.],
                              [3.,2.],
                              [8.,9.]], dtype = tf.float16)#specify the data type with dtype paramet

another_matrix 

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
# whats the number of dimension of another_matrix
another_matrix.ndim
# we can see the pattern that number of dimensions is same as total number in shape

2

In [ ]:
# lets create a tensor
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                       [[7,8,9],
                        [10,11,12]],
                       [[13,14,15],
                        [16,17,18]]])

tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
#check number of dimensions of tensor
tensor.ndim

3

Whta we've created so far:
* Scalar : a single number
* Vector : a number with direction(e.g wind speed and direction)
* Matrix : a 2-dimensional array of numbers
* Tensor : an n-dimensional array of number(where n can be any number, a 0-dimensional tensor is a scalar,1-dimensional tensor is a vector)

# creating tensors with tf.Variable

In [ ]:
#craete the same tensor with tf.Variable() as above
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])

changeable_tensor , unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
#lets try to change one of the elements in our changeable tensor
changeable_tensor[0] = 7
changeable_tensor

TypeError: ignored

In [ ]:
# how about we try .assign
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
# lets try chage our unchangeable tensor
unchangeable_tensor[0] = 7

TypeError: ignored

In [ ]:
 # lets try chage our unchangeable tensor with assign
unchangeable_tensor[0].assign(7)
unchangeable_tensor

AttributeError: ignored

### Creating random tensors

Random tensors are tensors of some abitrary size which contains random numbers

In [ ]:
# create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal(shape=(3,2))
random_1
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))

# are they equal?
random_1 , random_2 , random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order of elements in a tensor

In [ ]:
# shuffle a tensor (valuable for when you want to shuffle your data so the inherent order doesnt effect learning)

not_shuffled = tf.constant([[10,7],
                            [3,4],
                            [2,5]])
not_shuffled.ndim , not_shuffled

(2, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4],
        [ 2,  5]], dtype=int32)>)

In [ ]:
# shuffle our non-shuffled tensor
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [10,  7],
       [ 2,  5]], dtype=int32)>

In [ ]:
# shuffle our non-shuffled tensor running again
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled,seed = 42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [ ]:
# without setting goabl seed , we are not getting consistent random values

# difference between operational seed and global seed 
Operations that rely on a random seed actually derive it from two seeds: the global and operation-level seeds. This sets the global seed.

Its interactions with operation-level seeds is as follows:

* If neither the global seed nor the operation seed is set: A randomly picked seed is used for this op.
* If the global seed is set, but the operation seed is not: The system deterministically picks an operation seed in conjunction with the global seed so that it gets a unique random sequence. Within the same version of tensorflow and user code, this sequence is deterministic. However across different versions, this sequence might change. If the code depends on particular seeds to work, specify both global and operation-level seeds explicitly.
* If the operation seed is set, but the global seed is not set: A default global seed and the specified operation seed are used to determine the random sequence.
* If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence.

In [ ]:
tf.random.shuffle(not_shuffled , seed=42) # we get different order each time wtih this

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
tf.random.set_seed(42)# global level random seed
tf.random.shuffle(not_shuffled , seed=42)# operation level random seed
# now we get consistent random sequence

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

> It looks like if we eant our shuffled tensors to be in the same order m we've got to use global level random seed as well as operational level random seed

## other ways to make tensors

In [ ]:
# create a tensor of all ones
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
# create a tensors of all zeros
tf.zeros(shape = (3,4))
# shape could be passed with [] or () brackets

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### Turn numpy array into tensors

The main difference between numoy as tensorflow is that tensors can be run on a GPU (much faster for numerical computing)

In [ ]:
# you can turn numpy array into tensors

import numpy as np
numpy_A = np.arange(1,25,dtype=np.int32)
numpy_A
#X = tf.constant(some_matrix), capital for matrix or tensors
#y = t.constant(vector), non-capital for vectors

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant(numpy_A)
A,A.ndim

(<tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>, 1)

In [ ]:
B = tf.constant(numpy_A , shape =(2,3,4)) # 2 - blocks , where each block has 3 rows of element which conatins 
#4 elements
#shape = (a,b,c) - a-blocks , b-row , c-col
B,B.ndim

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>, 3)

In [ ]:
C = tf.constant(numpy_A , shape=(12,1,2))
C , C.ndim

(<tf.Tensor: shape=(12, 1, 2), dtype=int32, numpy=
 array([[[ 1,  2]],
 
        [[ 3,  4]],
 
        [[ 5,  6]],
 
        [[ 7,  8]],
 
        [[ 9, 10]],
 
        [[11, 12]],
 
        [[13, 14]],
 
        [[15, 16]],
 
        [[17, 18]],
 
        [[19, 20]],
 
        [[21, 22]],
 
        [[23, 24]]], dtype=int32)>, 3)

In [ ]:
D = tf.constant(numpy_A,shape=(12,2))
D,D.ndim

(<tf.Tensor: shape=(12, 2), dtype=int32, numpy=
 array([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20],
        [21, 22],
        [23, 24]], dtype=int32)>, 2)

### Getting information from your tensors(tensor attribues)

When dealing with tensors you probably want to be aware of the following attributes:
* shape
* rank
* axis or dimension
* size

In [ ]:
D.shape

TensorShape([12, 2])

In [ ]:
tf.size(D)

<tf.Tensor: shape=(), dtype=int32, numpy=24>

In [ ]:
# create a rank 4 tensor( 4 dimensions)
rank_4_tensor = tf.zeros(shape = [2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[0] # axis

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
# rank of a tensor
tf.rank(rank_4_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [ ]:
rank_4_tensor.shape , rank_4_tensor.ndim , tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
2*3*4*5

120

In [ ]:
#Get various attributes of our tensor
print('Datatype of every elements:' , rank_4_tensor.dtype)
print('Number if dimensions(rank):' , rank_4_tensor.ndim)
print('Shaoe of tensors:' , rank_4_tensor.shape)
print('Elements along the 0th axis:',rank_4_tensor.shape[0])
print('Elements aling the last axis:' , rank_4_tensor.shape[-1])
print('Total number of elements in our tensor:' , tf.size(rank_4_tensor))
print('Total number of elements in our tensor as numpy:' , tf.size(rank_4_tensor).numpy())

Datatype of every elements: <dtype: 'float32'>
Number if dimensions(rank): 4
Shaoe of tensors: (2, 3, 4, 5)
Elements along the 0th axis: 2
Elements aling the last axis: 5
Total number of elements in our tensor: tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in our tensor as numpy: 120


### Indexing and Exapnding tensors

* Tensors can be indexed just like python lists

In [ ]:
# get the first 2 elements of each dimensions
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
# get the first element from each dimensions from each index except from the final one
rank_4_tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
# get the firtst element from each dimensions , from each index except from the second last one
rank_4_tensor[:1,:1,:,:1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [ ]:
# Create a rank 2 tensor(2 dimension)
tf.random.set_seed(42)
rank_2_tensor = tf.constant(tf.random.uniform(shape=[2,2],seed=42))
rank_2_tensor , rank_2_tensor.ndim

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[0.4163028 , 0.26858163],
        [0.47968316, 0.36457133]], dtype=float32)>, 2)

In [ ]:
rank_2_tensor.shape , tf.size(rank_2_tensor)

(TensorShape([2, 2]), <tf.Tensor: shape=(), dtype=int32, numpy=4>)

In [ ]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.4163028 , 0.26858163],
       [0.47968316, 0.36457133]], dtype=float32)>

In [ ]:
# get the last item of each of our rank 2 tensor
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0.26858163, 0.36457133], dtype=float32)>

In [ ]:
#Add in extra dimension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[... , tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=float32, numpy=
array([[[0.4163028 ],
        [0.26858163]],

       [[0.47968316],
        [0.36457133]]], dtype=float32)>

In [ ]:
# list[:,:] is same as list[...], ie every axis before the last one, include those and add a new axis
# on the end
# for above example we would have something like follwoing
# rank_2_tensor[:,:,tf.newaxis] --> rank_2_tensor[...,tf.newaxis]
# in the first code, we are explicitly telling to make a new axis after 1st and 2nd
# but in second code, we are saying get all the axis and make a new axis after all present axis.

In [ ]:
# atlernative to t.newaxis

tf.expand_dims(rank_2_tensor,axis=-1) # -1 means expans the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=float32, numpy=
array([[[0.4163028 ],
        [0.26858163]],

       [[0.47968316],
        [0.36457133]]], dtype=float32)>

In [ ]:
tf.expand_dims(rank_2_tensor,axis=0) # expand the 0th axis

<tf.Tensor: shape=(1, 2, 2), dtype=float32, numpy=
array([[[0.4163028 , 0.26858163],
        [0.47968316, 0.36457133]]], dtype=float32)>

In [ ]:
tf.expand_dims(rank_2_tensor,axis=1) # expans the 1st axis

<tf.Tensor: shape=(2, 1, 2), dtype=float32, numpy=
array([[[0.4163028 , 0.26858163]],

       [[0.47968316, 0.36457133]]], dtype=float32)>

### Manipulating tensors (tensor operations)

** basic operation **

`+` , `-` , `*` , `/`



In [ ]:
# you can add values to a tensor using the addition operator
tensor = tf.constant([[10,7],
                      [3,4]])

tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
# Original tensor is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
# Multiplication also works
tensor*10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
# Substraction if you want
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [ ]:
# we can use the tensorflow buitlin functions too

tf.multiply(tensor , 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
# even after usng tensorflow functions, the original tensor is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

**Matrix Multiplication**

In machine learning, matrix multiplication is one of the most common operation

There are tow rules our tenosr needs to fulfill i we're going to matrix multiply them : 

* The inner dimensions must match 
* The resuting matrix has the shape of the outer dimensions

In [ ]:
# martrix multiplication in tensorflow

print(tensor)
tf.matmul(tensor,tensor) # this is the dot product

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
# output above is different from if we did the following
tensor*tensor # this is the element wise multiplication

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

In [ ]:
# matrix multiplication with python operator '@'
A = tf.constant([[[1,2,5],
                  [7,2,1],
                  [3,3,3]]])
B = tf.constant([[[3,5],
                 [6,7],
                 [1,8]]])

print(A@B) # python dot product (for matrix multiplication)
print(tf.matmul(A,B))

tf.Tensor(
[[[20 59]
  [34 57]
  [30 60]]], shape=(1, 3, 2), dtype=int32)
tf.Tensor(
[[[20 59]
  [34 57]
  [30 60]]], shape=(1, 3, 2), dtype=int32)


In [ ]:

X = tf.constant([[1,2],
                  [3,4],
                  [5,6]])
Y = tf.constant([[7,8],
                  [9,10],
                  [11,12]])
X , Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [ ]:
# try to multiply tensors with same shape
tf.matmul(X,Y)

InvalidArgumentError: ignored

In [ ]:
# correcting the above code
tf.matmul(X,tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [ ]:
tf.reshape(Y,shape=[2,3])

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [ ]:
# tf.reshape does not rearrange the dimensions of the tensor so if we get sometihing 
# like above where the sequence of the data buffer of original data
# has not changed , only the shape has been changed
tf.matmul(X , tf.reshape(Y ,shape=[2,3]))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
tf.reshape(Y,shape=[2,3])

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [ ]:
tf.reshape(X,shape=[2,3])

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [ ]:
tf.matmul(X,tf.reshape(Y,shape=[2,3]))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
# changing shapes of x and seperately changing shape of y
tf.matmul(tf.reshape(X,shape=[2,3]),Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [ ]:
# we can do same with transpose but ther eis a difference between them
X , tf.transpose(X) , tf.reshape(X,shape=[2,3])

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [ ]:
# transpose flips the axes while the reshape shuffels the tensor into the shape we want

In [ ]:
tf.matmul(tf.transpose(X),Y) 

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

### The dot product

Matrix multiplication is also referred to as the dot product
you can perform matrix multiplication using:

* `tf.matmul`
* `tf.tensordot`

In [ ]:
# perform the dot product on x and y ( requires x or y to be transposed)
tf.tensordot(tf.transpose(X), Y , axes = 1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

Generally, when performing matrix multiplication on two tensors ans one of the axes doesn't line up , you will transpose(rather than reshape) one of the tensors to get satisfy the matrix maultiplication rule

In [ ]:
########################################################################################

## changing the datatype of a tensor

In [ ]:
# Create a new tensor with default datatype(float32)

A = tf.constant([1.7,7.4])
print(A.dtype)

<dtype: 'float32'>


In [ ]:
B = tf.constant([2,3])
print(B.dtype)

<dtype: 'int32'>


In [ ]:
# change from float32 to float 16 (reduce precision, 32 bit precision - google)
B = tf.cast(B , dtype = tf.float16)
print(B.dtype)

<dtype: 'float16'>


In [ ]:
# change from int32 to float32
C = tf.constant([7,10])
D = tf.cast(C , dtype=tf.float32)
print(C.dtype , D.dtype)


<dtype: 'int32'> <dtype: 'float32'>


### Tensor aggregation 

Aggregrating tensors = condensing them from multiple values down to a smaller amaount of values

In [ ]:
# Getting the absolute values
A = tf.constant([-7,-10])
A

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [ ]:
# get the absolute values
tf.abs(A)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Lets go through the following forms of aggregration:
* get the minimum
* get the maximum
* get the mean 
* get the sum 

In [ ]:
# creating a new tensor for aggregration

tensor_agg = tf.constant(np.arange(25),shape=[5,5],dtype = tf.int32)
tensor_agg

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]], dtype=int32)>

In [ ]:
tensor_min = tf.reduce_min(tensor_agg)
tensor_min

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [ ]:
tensor_max = tf.reduce_max(tensor_agg)
tensor_max

<tf.Tensor: shape=(), dtype=int32, numpy=24>

In [ ]:
tensor_mean = tf.reduce_mean(tensor_agg)
tensor_mean

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [ ]:
tensor_sum = tf.reduce_sum(tf.cast(tensor_agg , dtype=tf.int64))
tensor_sum

<tf.Tensor: shape=(), dtype=int64, numpy=300>

In [ ]:
# find the standard deviation of a tensor
# here we get type error if we pass int32 or int64
tensor_std = tf.math.reduce_std(tf.cast(tensor_agg , dtype=tf.float32))
tensor_std

<tf.Tensor: shape=(), dtype=float32, numpy=7.2111025>

In [ ]:
# find the variance of a tensor
#tf.reduce_variance wont work
import tensorflow_probability as tfp
tensor_variance = tfp.stats.variance(tensor_agg)
tensor_variance

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([50, 50, 50, 50, 50], dtype=int32)>

In [ ]:
# another method for variance
tensor_variance_1 = tf.math.reduce_variance(tf.cast(tensor_agg, dtype= tf.float32))
tensor_variance_1

<tf.Tensor: shape=(), dtype=float32, numpy=52.0>

In [ ]:
tensor_agg_1 = tf.constant(np.random.randint(0,100 , size = 50))
tensor_agg_1

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([50, 91, 79, 33, 36, 19, 55, 49, 71, 99, 69, 89, 74, 93, 85, 88, 60,
       93, 61, 34, 82, 47, 69, 43, 28, 45, 97, 42, 93, 40, 53, 45, 32, 82,
        2, 29, 59, 55, 94, 93, 37, 60, 95, 49, 97, 61, 12,  6, 60, 61])>

In [ ]:
tensor_agg_1.shape , tensor_agg_1.ndim , tf.size(tensor_agg_1)

(TensorShape([50]), 1, <tf.Tensor: shape=(), dtype=int32, numpy=50>)

**Find the positional minimum and maximum of a tensor (argmin, argmax)**





In [ ]:
tensor_agg

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]], dtype=int32)>

In [ ]:
tensor_argmin = tf.math.argmin(tensor_agg)
tensor_argmin

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([0, 0, 0, 0, 0])>

In [ ]:
tensor_argmax = tf.math.argmax(tensor_agg)
tensor_argmax

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([4, 4, 4, 4, 4])>

In [ ]:
#applying above to a new tensor
tf.random.set_seed(42)
F = tf.random.uniform(shape = [50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
F_argmax = tf.argmax(F)
F_argmax

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
F_argmin = tf.argmin(F)
F_argmin

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [ ]:
# indexing maximum and minimum
F[tf.argmax(F)] , F[tf.argmin(F)]

(<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>)

In [ ]:
F.ndim

1

In [ ]:
tf.rank(F)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [ ]:
tf.reduce_max(F) , tf.reduce_min(F)# this matchs the above values


(<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>)

### Squeezing a tensor( removing all 1 - dimension axes)

* removing all single dimensions


In [ ]:
# create a tensor to get started
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [ ]:
G_squeezed = tf.squeeze(G)
G_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
G_squeezed.shape

TensorShape([50])

### One-hot encoding tensors

In [ ]:
some_list = [0,1,2,3] # could be red , green , blue, purple

# one hot encode our list of indices
tf.one_hot(some_list,depth = len(some_list))

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
# changing the depth value for above code
tf.one_hot(some_list,depth=2)

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [ ]:
# specify custome values for one hot encoding

tf.one_hot(some_list , depth = 4,on_value='yo I love deep learning',off_value = 'I also like to dance')

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'yo I love deep learning', b'I also like to dance',
        b'I also like to dance', b'I also like to dance'],
       [b'I also like to dance', b'yo I love deep learning',
        b'I also like to dance', b'I also like to dance'],
       [b'I also like to dance', b'I also like to dance',
        b'yo I love deep learning', b'I also like to dance'],
       [b'I also like to dance', b'I also like to dance',
        b'I also like to dance', b'yo I love deep learning']],
      dtype=object)>

### Squaring , log , square root

In [ ]:
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
# square it
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
# square root( will error, method require non -int type )
tf.sqrt((H))

InvalidArgumentError: ignored

In [ ]:
# square root
tf.sqrt(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

In [ ]:
# log ( will have the smae error as above for sqrt)
tf.math.log(H)

InvalidArgumentError: ignored

In [ ]:
tf.math.log(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### tensorflow and numpy compatibility


Tensorflow interacts beautifully with NumPy arrays

In [ ]:
J = tf.constant(np.array([3.,7.,10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [ ]:
# convert our tensor back to our numpy array
np.array(J) , type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
# convert tensor J to a numpy array
J.numpy() , type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
# if we want to do some type of operation and it doesn't work with tensor and we 
# know it could work with numpy then we may convert the tensor into numpy and do the 
# operation
J.numpy()[2] # slicing the array

10.0

In [ ]:
# Deafult types of each are slightly different

numpy_J = tf.constant( np.array([3.,7.,10.]))
tensor_J = tf.constant([3.,7.,10.])

# check the data type of each 

numpy_J.dtype , tensor_J.dtype

(tf.float64, tf.float32)

### Finding access to GPUs

In [ ]:
tf.test.is_gpu_available()

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.


False

In [ ]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [ ]:
!nvidia-smi

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



### Tensorflow FUndamentals Exercise

In [ ]:
# 1)
vector = tf.constant([1.])
scalar = tf.constant([1.,2.,3.])
matrix = tf.constant([[1.,2.,3.],
                      [4.,5.,6.]])
tensor = tf.constant(np.arange(24),shape=(1,2,3,4))
print(vector,
scalar,
matrix,
tensor)

tf.Tensor([1.], shape=(1,), dtype=float32) tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32) tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32) tf.Tensor(
[[[[ 0  1  2  3]
   [ 4  5  6  7]
   [ 8  9 10 11]]

  [[12 13 14 15]
   [16 17 18 19]
   [20 21 22 23]]]], shape=(1, 2, 3, 4), dtype=int64)


In [ ]:
#2)
tensor.shape , tf.rank(tensor) , tf.size(tensor), tensor.ndim

(TensorShape([1, 2, 3, 4]),
 <tf.Tensor: shape=(), dtype=int32, numpy=4>,
 <tf.Tensor: shape=(), dtype=int32, numpy=24>,
 4)

In [ ]:
#3)
tensorA = tf.constant(tf.random.uniform(shape=[5,300],minval =0,maxval=1))
tensorB = tf.constant(tf.random.uniform(shape=[5,300],minval=0,maxval=1))
tensorA , tensorB

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.7413678 , 0.62854624, 0.01738465, ..., 0.4851334 , 0.21059811,
         0.25082767],
        [0.10842848, 0.48783147, 0.8240961 , ..., 0.9204427 , 0.36046863,
         0.28176582],
        [0.7326695 , 0.46489418, 0.13622475, ..., 0.28130388, 0.63987684,
         0.9987265 ],
        [0.01447165, 0.7845044 , 0.33475304, ..., 0.56194997, 0.0209924 ,
         0.1740731 ],
        [0.90936875, 0.19861352, 0.9481231 , ..., 0.3573054 , 0.13161755,
         0.22565222]], dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.7402308 , 0.33938193, 0.5692506 , ..., 0.08656633, 0.19666708,
         0.7110305 ],
        [0.13257599, 0.81292987, 0.01284087, ..., 0.02695906, 0.2927854 ,
         0.06227863],
        [0.282601  , 0.47868013, 0.77569485, ..., 0.28239357, 0.632112  ,
         0.44452012],
        [0.02029276, 0.7841259 , 0.16919017, ..., 0.26143157, 0.43055534,
         0.47421408],
        [0.26160

In [ ]:
tensorA_min = tf.reduce_min(tensorA)
tensorB_min = tf.reduce_min(tensorB)
tensorA_max = tf.reduce_max(tensorA)
tensorB_max = tf.reduce_max(tensorB)
print(tensorA_min,tensorB_min) 
print('\n')
print(tensorA_max , tensorB_max)

tf.Tensor(0.000259161, shape=(), dtype=float32) tf.Tensor(0.0006545782, shape=(), dtype=float32)


tf.Tensor(0.9998193, shape=(), dtype=float32) tf.Tensor(0.99864674, shape=(), dtype=float32)


In [ ]:
#4)
tf.matmul(tensorA , tf.transpose(tensorB))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[72.63513 , 73.275154, 72.47874 , 73.895355, 77.069084],
       [76.14803 , 77.38722 , 76.156006, 78.477905, 77.93587 ],
       [74.061386, 75.79873 , 74.00405 , 74.95445 , 74.85766 ],
       [72.61861 , 77.07387 , 72.674484, 75.916084, 73.15647 ],
       [74.65547 , 76.221756, 75.43701 , 76.92053 , 76.65762 ]],
      dtype=float32)>

In [ ]:
#5)
tensorA@tf.transpose(tensorB)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[72.63513 , 73.275154, 72.47874 , 73.895355, 77.069084],
       [76.14803 , 77.38722 , 76.156006, 78.477905, 77.93587 ],
       [74.061386, 75.79873 , 74.00405 , 74.95445 , 74.85766 ],
       [72.61861 , 77.07387 , 72.674484, 75.916084, 73.15647 ],
       [74.65547 , 76.221756, 75.43701 , 76.92053 , 76.65762 ]],
      dtype=float32)>

In [ ]:
#6)
tensorC = tf.constant(tf.random.uniform(shape=[224,224,3],minval =0,maxval=1))
tensorC

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[8.0315602e-01, 4.9777734e-01, 3.7054038e-01],
        [9.1186738e-01, 6.3764203e-01, 1.8209696e-01],
        [6.3791955e-01, 2.7701473e-01, 4.2271137e-02],
        ...,
        [1.0830712e-01, 4.5979273e-01, 2.5716281e-01],
        [8.7138689e-01, 1.8434000e-01, 4.4757760e-01],
        [7.4110627e-02, 9.0852141e-01, 5.3693414e-01]],

       [[5.5596435e-01, 6.8776274e-01, 7.6051474e-02],
        [1.6737962e-01, 7.1785092e-01, 2.7642274e-01],
        [2.6995218e-01, 3.2203627e-01, 8.8224900e-01],
        ...,
        [4.8168826e-01, 5.0150025e-01, 8.6756039e-01],
        [4.1261053e-01, 1.2770486e-01, 5.8186901e-01],
        [2.5495613e-01, 3.9036548e-01, 9.8529553e-01]],

       [[8.0935180e-01, 1.9740558e-01, 3.5899937e-01],
        [1.1216915e-01, 9.1016293e-04, 3.6382091e-01],
        [5.1202202e-01, 3.9188230e-01, 8.8335538e-01],
        ...,
        [2.0133841e-01, 9.1663551e-01, 1.9890130e-01],
        [8.0388057e-01

In [ ]:
#7)
tensorC_min_1_axis = tf.reduce_min(tensorC , axis=1)
tensorC_max_1_axis = tf.reduce_max(tensorC,axis = 1)
tensorC_min_1_axis , tensorC_max_1_axis

(<tf.Tensor: shape=(224, 3), dtype=float32, numpy=
 array([[1.10803843e-02, 1.02496147e-02, 6.97255135e-04],
        [3.66926193e-04, 6.02853298e-03, 4.84395027e-03],
        [8.86380672e-03, 9.10162926e-04, 6.86645508e-05],
        [1.87039375e-04, 1.58452988e-03, 5.38277626e-03],
        [8.89182091e-04, 3.49676609e-03, 4.27591801e-03],
        [3.31401825e-05, 1.68085098e-04, 9.56428051e-03],
        [4.85968590e-03, 2.46119499e-03, 1.16758347e-02],
        [6.48498535e-05, 4.37498093e-05, 2.20274925e-03],
        [1.88767910e-03, 1.06034279e-02, 2.22861767e-03],
        [4.14001942e-03, 6.28113747e-03, 8.30888748e-04],
        [1.28412247e-03, 7.01785088e-04, 1.09546185e-02],
        [5.67162037e-03, 7.28201866e-03, 4.90629673e-03],
        [8.90970230e-03, 3.02195549e-04, 5.37037849e-03],
        [9.31501389e-04, 5.12826443e-03, 4.44579124e-03],
        [1.33991241e-03, 2.27785110e-03, 4.25422192e-03],
        [1.10207796e-02, 5.41090965e-04, 4.89103794e-03],
        [4.62865829e-